"""Add cluster_id to Scenario

Revision ID: f02aae85c4f0
Revises: 32144ad4e222
Create Date: 2026-06-30 20:34:06.944239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02aae85c4f0'
down_revision: Union[str, Sequence[str], None] = '32144ad4e222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('cluster_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'cluster_id')
    # ### end Alembic commands ###
